### ISSUE TITLE
.env file not found

### ISSUE THREAD

**Issue by placecodex** [tatumio/tatum-php#1]
Fatal error: Uncaught TatumException: You need to set your Network from your .env file! in C:\laragon\www\tatum\vendor\tatumio\tatum-php\src\Tatum.php:57 Stack trace: #0 C:\laragon\www\tatum\vendor\tatumio\tatum-php\src\Tatum.php(42): Tatum\Tatum->InitTatum() #1 C:\laragon\www\tatum\index.php(104): Tatum\Tatum->__construct() #2 [internal function]: {closure}()

**Comment by HighBreedTech** [comment]
@placecodex sorry for very late response, if anyone is facing this same issue please do not hesitate to speak so i will tell you the solution to this

**Comment by HighBreedTech** [comment]
create .env file on your Root folder 

put
```bash
# Enter TATUM API KEY for Mainnet and Testnet then set your network type to mainnet or testnet
TATUM_API_KEY=
TATUM_TESTNET_API_KEY=
NETWORK=testnet
LOG_EXCEPTION=true
```

**Comment by HighBreedTech** [comment]
thats all you need to solve this issue, the lib was said to disable creating of .env by default, so you have to do this manually the code in found inside example.env

**Comment by HighBreedTech** [comment]
```bash
Fatal error: Uncaught TatumException: You need to set your Network from your .env file! in C:\laragon\www\tatum\vendor\tatumio\tatum-php\src\Tatum.php:57 Stack trace: #0 C:\laragon\www\tatum\vendor\tatumio\tatum-php\src\Tatum.php(42): Tatum\Tatum->InitTatum() #1 C:\laragon\www\tatum\index.php(104): Tatum\Tatum->__construct() #2 [internal function]: {closure}()
```

according to this error above .env needed to be created inside 
```bash
C:\laragon\www\tatum
```

and value need to be inserted then fill all value correctly with your tatum api key and network everything will work correctly

```bash
# Enter TATUM API KEY for Mainnet and Testnet then set your network type to mainnet or testnet
TATUM_API_KEY=
TATUM_TESTNET_API_KEY=
NETWORK=testnet
LOG_EXCEPTION=true
```

**Comment by HighBreedTech** [comment]
but normally the script create .example.env which contains the .env example value, if you have hidden files to not display on your pc, make it display hidden files then you will see the .example.env then create the .env yourself by copying the .example.env file content to it.

**Comment by mark-jivko** [comment]
PHP SDK version `0.1.0` was archived.
