### ISSUE TITLE
php-mcrypt not available from source

### ISSUE THREAD

**Issue by thfbinx** [tatumio/tatum-php#2]
After cloning the repo into a folder I opened the read me to finish the install, upon running the command 

"apt-get install php php-gmp php-mbstring php-mcrypt"

I was returned this error . 

"Package php-mcrypt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-mcrypt' has no installation candidate"

So is there another program that can accomplish this same thing or perhaps another source?

**Comment by HighBreedTech** [comment]
sorry for late response,
based on php website https://www.php.net/manual/en/book.mcrypt.php you will specify the version with it example
 `apt-get install php5-mcrypt`

**Comment by HighBreedTech** [comment]
Regarding #1 check on #1 to see the solution
